apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/cluster
  # - github.com/utilitywarehouse/flatcar-manifests//base/cluster?ref=master
  - ../base/namespaced
  # - github.com/utilitywarehouse/flatcar-manifests//base/namespaced?ref=master
  - ../base/nebraska
  # - github.com/utilitywarehouse/flatcar-manifests//base/nebraska?ref=master
resources:
  - rbac.yaml
secretGenerator:
  - name: nebraska-postgres
    type: Opaque
    envs:
      - secrets/nebraska-postgres.env
  - name: nebraska
    type: Opaque
    envs:
      - secrets/nebraska.env
