apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebraska-configurer
spec:
  template:
    spec:
      containers:
        - name: configurer
          env:
            - name: PACKAGE_VERSION
              value: "2605.12.0"
            - name: CHANNEL_NAME
              value: "stable-tested"
            - name: GROUP_NAME
              value: "stable-tested"
            - name: UPDATES_ENABLED
              value: "true"
