apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nebraska-postgres.yaml
  - nebraska.yaml
configMapGenerator:
  - name: nebraska-postgres
    files:
      - resources/nebraska.sql
