apiVersion: v1
kind: Service
metadata:
  name: nebraska-postgres
spec:
  selector:
    app: nebraska-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nebraska-postgres
spec:
  serviceName: "nebraska-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: nebraska-postgres
  template:
    metadata:
      labels:
        app: nebraska-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nebraska-postgres
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /data/pgdata
          resources:
            requests:
              memory: "32Mi"
              cpu: "0m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-init
          configMap:
            name: nebraska-postgres
            items:
              - key: nebraska.sql
                path: nebraska.sql
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
