apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/flatcar-linux-update-agent/namespaced/
  - ../../common/flatcar-linux-update-operator/namespaced/
  - ../../common/flatcar-update-ctl/namespaced/
  - flatcar-google-image-uploader.yaml
