kind: ServiceAccount
apiVersion: v1
metadata:
  name: flatcar-update-ctl
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flatcar-update-ctl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flatcar-update-ctl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flatcar-update-ctl
    spec:
      serviceAccountName: flatcar-update-ctl
      nodeSelector:
        flatcar-linux-update.v1.flatcar-linux.net/before-reboot: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: flatcar-update-ctl
          image: quay.io/utilitywarehouse/flatcar-toolkit
          args:
            - update-ctl
          volumeMounts:
            - mountPath: /usr/bin/update_engine_client
              name: update-engine-client
              readOnly: true
            - mountPath: /var/run/dbus
              name: var-run-dbus
              readOnly: true
            - mountPath: /lib64
              name: lib64
              readOnly: true
          env:
            - name: DESIRED_VERSION
              value: "current"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: update-engine-client
          hostPath:
            path: /usr/bin/update_engine_client
        - name: var-run-dbus
          hostPath:
            path: /var/run/dbus
        - name: lib64
          hostPath:
            path: /lib64
